import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service – MatchMeter',
  description: 'Read the MatchMeter Terms of Service.',
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-extrabold text-gray-800 mb-2">Terms of Service</h1>
      <p className="text-gray-400 text-sm mb-8">Last updated: May 2025</p>

      <div className="space-y-6 text-gray-700 text-base leading-relaxed">
        <p>
          By accessing and using MatchMeter (&quot;the Site&quot;), you agree to be bound by these Terms of Service. If you do not
          agree with any of these terms, please do not use the Site.
        </p>

        <h2 className="text-xl font-bold text-gray-800">1. Entertainment Purpose Only</h2>
        <p>
          All results generated by MatchMeter are for <strong>entertainment purposes only</strong>. The compatibility scores
          are algorithmically produced from name inputs and have no scientific, psychological, or astrological basis.
          Results should not be used to make any real-life decisions.
        </p>

        <h2 className="text-xl font-bold text-gray-800">2. No Guarantees</h2>
        <p>
          MatchMeter makes no warranties or guarantees of any kind, express or implied, regarding the accuracy, completeness,
          or reliability of the results provided. All results are provided &quot;as is&quot; without any warranty.
        </p>

        <h2 className="text-xl font-bold text-gray-800">3. Use at Your Own Risk</h2>
        <p>
          Your use of MatchMeter is entirely at your own risk. We shall not be held liable for any direct, indirect, incidental,
          or consequential damages arising from your use of the Site or reliance on its results.
        </p>

        <h2 className="text-xl font-bold text-gray-800">4. User Conduct</h2>
        <p>You agree not to use MatchMeter to:</p>
        <ul className="list-disc list-inside space-y-1">
          <li>Harass, bully, or harm other individuals</li>
          <li>Spread false or defamatory content</li>
          <li>Attempt to reverse-engineer or hack the Site</li>
          <li>Violate any applicable laws or regulations</li>
        </ul>

        <h2 className="text-xl font-bold text-gray-800">5. Intellectual Property</h2>
        <p>
          All content on MatchMeter, including but not limited to text, design, code, and graphics, is the property of
          MatchMeter and is protected by applicable intellectual property laws. You may not reproduce, distribute, or
          create derivative works without our explicit written permission.
        </p>

        <h2 className="text-xl font-bold text-gray-800">6. Third-Party Links</h2>
        <p>
          The Site may contain links to third-party websites. MatchMeter is not responsible for the content or privacy
          practices of those sites. Visiting third-party links is at your own risk.
        </p>

        <h2 className="text-xl font-bold text-gray-800">7. Changes to These Terms</h2>
        <p>
          We reserve the right to modify these Terms at any time. Continued use of the Site following any changes
          constitutes acceptance of the updated Terms.
        </p>

        <h2 className="text-xl font-bold text-gray-800">8. Contact</h2>
        <p>
          For any questions regarding these Terms, contact us at{' '}
          <a href="mailto:hello@matchmeter.app" className="text-pink-600 hover:underline">
            hello@matchmeter.app
          </a>.
        </p>
      </div>
    </div>
  );
}
