import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer – MatchMeter',
  description: 'Read the MatchMeter Disclaimer. Results are for entertainment purposes only.',
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-extrabold text-gray-800 mb-2">Disclaimer</h1>
      <p className="text-gray-400 text-sm mb-8">Last updated: May 2025</p>

      <div className="space-y-6 text-gray-700 text-base leading-relaxed">
        <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-5">
          <p className="font-semibold text-yellow-800">
            This tool is for entertainment purposes only. The results generated by MatchMeter are not scientifically
            accurate and should not be taken seriously.
          </p>
        </div>

        <h2 className="text-xl font-bold text-gray-800">No Scientific Basis</h2>
        <p>
          The compatibility scores shown on MatchMeter are generated by a simple algorithm that processes the characters
          in two names. This method has no basis in science, psychology, astrology, numerology, or any other discipline.
          The scores are entirely arbitrary and designed solely to be fun and entertaining.
        </p>

        <h2 className="text-xl font-bold text-gray-800">Not Professional Advice</h2>
        <p>
          Nothing on MatchMeter constitutes professional, medical, psychological, or relationship advice. The results
          should never be used to make decisions about relationships, friendships, or any aspect of your personal life.
          If you have concerns about a relationship, please consult a qualified professional.
        </p>

        <h2 className="text-xl font-bold text-gray-800">No Liability</h2>
        <p>
          MatchMeter and its creators accept no responsibility for any actions taken based on the results produced by
          this tool. By using the Site, you acknowledge that all results are for entertainment purposes only and agree
          not to hold MatchMeter liable for any outcomes.
        </p>

        <h2 className="text-xl font-bold text-gray-800">Third-Party Advertising</h2>
        <p>
          MatchMeter may display advertisements from third-party providers such as Google AdSense. The views and content
          of these advertisements do not represent the opinions or endorsements of MatchMeter.
        </p>

        <h2 className="text-xl font-bold text-gray-800">Questions?</h2>
        <p>
          If you have any questions about this disclaimer, contact us at{' '}
          <a href="mailto:hello@matchmeter.app" className="text-pink-600 hover:underline">
            hello@matchmeter.app
          </a>.
        </p>
      </div>
    </div>
  );
}
